### ISSUE TITLE
Deadline one

### ISSUE THREAD

**Issue by sje30** [bioinformatics-core-shared-training/rep-research-masterclass#1]
hi guys, didn't we have an internal deadline of May 1?  Gord?

**Comment by gdbzork** [comment]
You were serious about that? ;)

Sorry, I was off for a few days with some sort of stomach bug and got
behind.

I can give you the basic outline, though.  I see my section (tools) as
having 3 phases:
1) Source code management -- introduce the idea, and a quick intro to Git,
plus mention of svn.
2) Reproducing the analysis -- examples of Knitr, mention of Ruffus, and a
few other pipeline tools
3) Reproducing the environment -- Docker, mention of EasyBuild, cloud
images, etc.

Should fill a half hour pretty easily... just give them a taste of the sort
of tools that are available.

What do you think?
- Gord

**Comment by sje30** [comment]
Which

**Comment by sje30** [comment]
Yes, that looks great.  (You are talking second, right)? If Florian then introduces the big picture first, 
after Gord's talk, I can then follow up with examples of Knitr and Docker.  I assume the audience will be mostly biologically-minded, rather than techy, so we need to ensure we keep things understandable.

**Comment by florianmarkowetz** [comment]
Yes, that's true: I go first, then Gord, then you. I will talk about the Duke Saga and give them reasons why to care about reproducibility. They should then be much more motivated to hear about the tools and the examples.

**Comment by sje30** [comment]
Gord, are you planning (or looking for) a docker demo as part of our
thing next week?  I thought I had one, but its currently broken; will
need to fix it anyway, but if you need one (or if we agree we should all
get one) then I need to fix it myself asap.

S

**Comment by sje30** [comment]
bug fixed.  anyone else runnign docker, and care to try:

```
docker run -d -p 8787:8787 sje30/waverepo
open http://192.168.59.103:8787/
```

login with "rstudio" as both name and password.

then open waverepo/paper/waverepo_paper.Rnw file and hit "Compile PDF".

S

**Comment by gdbzork** [comment]
Hi,

I was under the impression that you were going to include the docker demo
as part of your presentation (and your slides seem to reflect that...) so
I'll just mention it briefly in my section.

Cheers,
- Gord
