### ISSUE TITLE
incorrect date in filename?

### ISSUE THREAD

**Issue by sje30** [bioinformatics-core-shared-training/rep-research-masterclass#3]
`rep-research-masterclass/PDM 10th July 15 v3.pdf`

why is the above filename called the 10th July?  aren't we speaking on the 8th?

**Comment by markdunning** [comment]
don't know sorry. possibly an error at their end? It's definitely down for the 8th though.

http://talks.cam.ac.uk/talk/index/59722

**Comment by sje30** [comment]
ok.
